version: "3.8"
services: 
  app:
    container_name: seminar221
    build: 
      context: .
      args: 
        - JULIA_VERSION=1.8.1
    ports: 
      - "2218:2218"
    volumes: 
      - .:/home/julia/project
