version: "3.8"
services: 
  app:
    container_name: testingmyjulia
    build: 
      context: .
      args: 
        - JULIA_VERSION=1.5.3
    ports: 
      - "1235:1235"
    volumes: 
      - .:/home/julia/project
